version: '3.8'
services:
  api:
    image: goliath02/bsc_registration:latest
    container_name: bsc-registration-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/app/logs
    restart: always


  nginx:
    image: nginx:1.27.2-alpine-slim
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    restart: always


